# Generated by Django 5.2 on 2025-06-20 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="get_audio_path"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="get_photo_path"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="get_video_path"),
                ),
            ],
            options={
                "verbose_name": "Точка",
                "verbose_name_plural": "Точки",
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.FloatField(blank=True, help_text="Широта", null=True),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, help_text="Долгота", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocodes",
                        to="core.quest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.point"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.route"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("route", "point")},
            },
        ),
        migrations.AddField(
            model_name="route",
            name="points",
            field=models.ManyToManyField(through="core.RoutePoint", to="core.point"),
        ),
        migrations.AddField(
            model_name="route",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_routes",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_points",
                to="core.user",
            ),
        ),
        migrations.CreateModel(
            name="UserQuestProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("photo", models.ImageField(upload_to="quest_photos/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На проверке"),
                            ("approved", "Подтверждено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("admin_comment", models.TextField(blank=True)),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.promocode",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quest"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_progress",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "quest")},
            },
        ),
    ]
