# Generated by Django 5.0.2 on 2025-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Широта', null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Долгота', null=True),
        ),
    ]
