# Generated by Django 5.2.4 on 2025-07-19 17:54

import core.models
import django.db.models.deletion
import uuid
import yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_audio_path),
        ),
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_photo_path),
        ),
        migrations.AlterField(
            model_name='point',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_video_path),
        ),
        migrations.CreateModel(
            name='PointAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_audio_path)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.point')),
            ],
        ),
        migrations.CreateModel(
            name='PointPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_photo_path)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.point')),
            ],
        ),
        migrations.CreateModel(
            name='PointVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_video_path)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.point')),
            ],
        ),
    ]
