# Generated by Django 5.2 on 2025-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="point",
            options={"verbose_name": "Точка", "verbose_name_plural": "Точки"},
        ),
        migrations.AlterField(
            model_name="point",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="get_audio_path"),
        ),
        migrations.AlterField(
            model_name="point",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="get_photo_path"),
        ),
        migrations.AlterField(
            model_name="point",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="get_video_path"),
        ),
    ]
