# Generated by Django 5.2 on 2025-07-22 13:45

import core.models
import yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_point_audio_file_alter_point_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=yandex_s3_storage.ClientDocsStorage(), upload_to=core.models.get_route_photo_path),
        ),
    ]
